---
- name: Launch ec2 instances
  gce:
    instance_names: test-1-121
    zone: us-central1-a
    machine_type: n1-standard-1
    image: debian-8
    state: active
    tags: abc,def
    service_account_email: "newgcp@artful-bonsai-198911.iam.gserviceaccount.com"
    credentials_file: "abc.json"
    project_id: "artful-bonsai-198911"
  register: ec2_created_vms

- name: Log ec2_created_vms
  debug:
    var: item
  with_items: "{{ ec2_created_vms.instances }}"
  when: verbose

#- name: Wait for SSH
#  wait_for:
#    host: "{{ item.public_dns_name }}"
#    port: 22
#    delay: 60
#    timeout: 320
#    state: started
#  with_items: "{{ ec2_created_vms.instances }}"
  #when: assign_public_ip

#- add_host:
#name: "{{ item.public_ip }}"
#    # ansible_user: "{{ ec2-user | default('ec2-user') }}"
    # ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"
 #   groups: ec2_hosts
#with_items: "{{ ec2_created_vms.instances }}"
